# Generated by Django 4.2.7 on 2023-11-13 20:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dislikes',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('id_user', models.IntegerField()),
                ('id_post', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Likes',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('id_user', models.IntegerField()),
                ('id_post', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('count_likes', models.IntegerField()),
                ('count_dislikes', models.IntegerField()),
                ('description', models.TextField()),
                ('publication_date', models.DateTimeField()),
                ('images', models.ImageField(upload_to='images/posts')),
            ],
        ),
        migrations.CreateModel(
            name='Registration',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('login', models.CharField(max_length=30)),
                ('password', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Tags',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.TextField()),
                ('link', models.TextField()),
                ('count_users', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='User_profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('avatar', models.ImageField(upload_to='images/avatars')),
                ('date_of_birth', models.DateTimeField()),
                ('about', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='PostHasTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DjangoGramm.post')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DjangoGramm.tags')),
            ],
        ),
    ]
