# Generated by Django 4.2.7 on 2023-11-14 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DjangoGramm', '0002_post_author_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_profile',
            name='login',
            field=models.CharField(default=None, max_length=30),
            preserve_default=False,
        ),
    ]
