# Generated by Django 4.2.7 on 2023-11-14 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DjangoGramm', '0003_user_profile_login'),
    ]

    operations = [
        migrations.AddField(
            model_name='registration',
            name='about',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='registration',
            name='avatar',
            field=models.ImageField(blank=True, upload_to='images/avatars'),
        ),
        migrations.AddField(
            model_name='registration',
            name='date_of_birth',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='registration',
            name='first_name',
            field=models.CharField(default=0, max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='registration',
            name='last_name',
            field=models.CharField(default=0, max_length=30),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='registration',
            name='login',
            field=models.CharField(max_length=30, unique=True),
        ),
    ]
