# Generated by Django 4.2.7 on 2023-11-15 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DjangoGramm', '0004_registration_about_registration_avatar_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User_profile',
        ),
        migrations.AddField(
            model_name='registration',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
